import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#570092",
        "on-primary": "#f1f2ff",
        "secondary-fixed": "#ffc69a",
        "secondary-fixed-dim": "#ffb375",
        "surface-container-highest": "#dbdde0",
        "tertiary-container": "#d09aff",
        "secondary-container": "#ffc69a",
        secondary: "#8c4a00",
        "tertiary-dim": "#731eb6",
        "primary-fixed": "#8ea6f0",
        "primary-container": "#8ea6f0",
        "primary-fixed-dim": "#8199e1",
        "surface-container-lowest": "#ffffff",
        "on-background": "#2d2f31",
        "primary-dim": "#344c8f",
        "secondary-dim": "#7b4000",
        "surface-tint": "#40589c",
        "tertiary-fixed": "#d09aff",
        "on-error-container": "#570008",
        "surface-container-low": "#f0f1f3",
        "on-secondary": "#fff0e7",
        "on-tertiary-container": "#4b007e",
        "inverse-on-surface": "#9c9d9f",
        error: "#b31b25",
        "error-dim": "#9f0519",
        surface: "#f6f6f8",
        "surface-container-high": "#e1e2e5",
        "on-surface-variant": "#5a5c5d",
        "surface-variant": "#dbdde0",
        "on-secondary-fixed-variant": "#7c4100",
        "on-primary-fixed": "#000929",
        "on-error": "#ffefee",
        primary: "#40589c",
        "surface-bright": "#f6f6f8",
        "on-tertiary-fixed": "#280047",
        "inverse-surface": "#0c0e10",
        "on-primary-container": "#022568",
        "surface-container": "#e7e8ea",
        "on-tertiary": "#fbefff",
        "on-secondary-container": "#6f3a00",
        "inverse-primary": "#8ea6f0",
        "on-surface": "#2d2f31",
        "on-primary-fixed-variant": "#112e71",
        "on-secondary-fixed": "#532a00",
        outline: "#757779",
        "error-container": "#fb5151",
        "tertiary-fixed-dim": "#c787ff",
        "outline-variant": "#acadaf",
        "surface-dim": "#d2d4d8",
        tertiary: "#802fc3",
        background: "#f6f6f8",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-plus-jakarta)", "sans-serif"],
        body: ["var(--font-lexend)", "sans-serif"],
        label: ["var(--font-lexend)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
